### ISSUE TITLE
anime.browser.js: Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by garbin** [stelatech/react-anime#4]
It requires a global React?

**Comment by kennetpostigo** [comment]
@garbin yes `React` and `anime` is required as they are peer dependecies of `react-anime. Refer to the codepen JS settings:
http://l.facebook.com/l.php?u=http%3A%2F%2Fcodepen.io%2Falaingalvan%2Fpen%2FEgjbKP%2F&h=DAQHiZkZ6

**Comment by garbin** [comment]
You means I should require React, animejs and expose them to Global scope? window.React, window.anime must exists?

**Comment by philpl** [comment]
UMD bundles require their peer dependency counterparts to be loaded already. Take a look at the `externals` definition [1] here: https://github.com/stelatech/react-anime/blob/master/webpack.browser.js

So if you're not bundling / resolving dependencies in another way you need to load their UMD bundles as well. Check out https://unpkg.com/

[1]: https://webpack.github.io/docs/library-and-externals.html

**Comment by kennetpostigo** [comment]
@garbin yes exactly that. Look at the settings in the codepen I linked and you should see that i'm importing react and anime from unpkg. @philpl exactly, you need to bring in the peer dependencies through unpkg because we don't bundle them with react-anime. If you use npm then the peer dependencies should be installed automatically.
